// Code generated by MockGen. DO NOT EDIT.
// Source: mellanox.go

// Package mock_mellanox is a generated GoMock package.
package mock_mellanox

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mellanox "github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/vendors/mellanox"
)

// MockMellanoxInterface is a mock of MellanoxInterface interface.
type MockMellanoxInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMellanoxInterfaceMockRecorder
}

// MockMellanoxInterfaceMockRecorder is the mock recorder for MockMellanoxInterface.
type MockMellanoxInterfaceMockRecorder struct {
	mock *MockMellanoxInterface
}

// NewMockMellanoxInterface creates a new mock instance.
func NewMockMellanoxInterface(ctrl *gomock.Controller) *MockMellanoxInterface {
	mock := &MockMellanoxInterface{ctrl: ctrl}
	mock.recorder = &MockMellanoxInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMellanoxInterface) EXPECT() *MockMellanoxInterfaceMockRecorder {
	return m.recorder
}

// GetMellanoxBlueFieldMode mocks base method.
func (m *MockMellanoxInterface) GetMellanoxBlueFieldMode(arg0 string) (mellanox.BlueFieldMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMellanoxBlueFieldMode", arg0)
	ret0, _ := ret[0].(mellanox.BlueFieldMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMellanoxBlueFieldMode indicates an expected call of GetMellanoxBlueFieldMode.
func (mr *MockMellanoxInterfaceMockRecorder) GetMellanoxBlueFieldMode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMellanoxBlueFieldMode", reflect.TypeOf((*MockMellanoxInterface)(nil).GetMellanoxBlueFieldMode), arg0)
}

// GetMlnxNicFwData mocks base method.
func (m *MockMellanoxInterface) GetMlnxNicFwData(pciAddress string) (*mellanox.MLXNic, *mellanox.MLXNic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMlnxNicFwData", pciAddress)
	ret0, _ := ret[0].(*mellanox.MLXNic)
	ret1, _ := ret[1].(*mellanox.MLXNic)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMlnxNicFwData indicates an expected call of GetMlnxNicFwData.
func (mr *MockMellanoxInterfaceMockRecorder) GetMlnxNicFwData(pciAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMlnxNicFwData", reflect.TypeOf((*MockMellanoxInterface)(nil).GetMlnxNicFwData), pciAddress)
}

// MLXConfigFW mocks base method.
func (m *MockMellanoxInterface) MLXConfigFW(attributesToChange map[string]mellanox.MLXNic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MLXConfigFW", attributesToChange)
	ret0, _ := ret[0].(error)
	return ret0
}

// MLXConfigFW indicates an expected call of MLXConfigFW.
func (mr *MockMellanoxInterfaceMockRecorder) MLXConfigFW(attributesToChange interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MLXConfigFW", reflect.TypeOf((*MockMellanoxInterface)(nil).MLXConfigFW), attributesToChange)
}

// MstConfigReadData mocks base method.
func (m *MockMellanoxInterface) MstConfigReadData(arg0 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MstConfigReadData", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MstConfigReadData indicates an expected call of MstConfigReadData.
func (mr *MockMellanoxInterfaceMockRecorder) MstConfigReadData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MstConfigReadData", reflect.TypeOf((*MockMellanoxInterface)(nil).MstConfigReadData), arg0)
}
