---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-exporter-sa
  namespace: {{.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-exporter-role
  namespace: {{.Namespace}}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - hostaccess
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-exporter-rb
  namespace: {{.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-exporter-role
subjects:
  - kind: ServiceAccount
    name: metrics-exporter-sa
    namespace: {{.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriov-metrics-kube-rbac-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-metrics-kube-rbac-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriov-metrics-kube-rbac-role
subjects:
- kind: ServiceAccount
  name: metrics-exporter-sa
  namespace: {{.Namespace}}
