// Code generated by MockGen. DO NOT EDIT.
// Source: platforms.go

// Package mock_platforms is a generated GoMock package.
package mock_platforms

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1"
	openshift "github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/platforms/openshift"
	versioned "github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned"
)

// MockPlatformHelperInterface is a mock of PlatformHelperInterface interface.
type MockPlatformHelperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPlatformHelperInterfaceMockRecorder
}

// MockPlatformHelperInterfaceMockRecorder is the mock recorder for MockPlatformHelperInterface.
type MockPlatformHelperInterfaceMockRecorder struct {
	mock *MockPlatformHelperInterface
}

// NewMockPlatformHelperInterface creates a new mock instance.
func NewMockPlatformHelperInterface(ctrl *gomock.Controller) *MockPlatformHelperInterface {
	mock := &MockPlatformHelperInterface{ctrl: ctrl}
	mock.recorder = &MockPlatformHelperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlatformHelperInterface) EXPECT() *MockPlatformHelperInterfaceMockRecorder {
	return m.recorder
}

// CreateOpenstackDevicesInfo mocks base method.
func (m *MockPlatformHelperInterface) CreateOpenstackDevicesInfo() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenstackDevicesInfo")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOpenstackDevicesInfo indicates an expected call of CreateOpenstackDevicesInfo.
func (mr *MockPlatformHelperInterfaceMockRecorder) CreateOpenstackDevicesInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenstackDevicesInfo", reflect.TypeOf((*MockPlatformHelperInterface)(nil).CreateOpenstackDevicesInfo))
}

// CreateOpenstackDevicesInfoFromNodeStatus mocks base method.
func (m *MockPlatformHelperInterface) CreateOpenstackDevicesInfoFromNodeStatus(arg0 *v1.SriovNetworkNodeState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateOpenstackDevicesInfoFromNodeStatus", arg0)
}

// CreateOpenstackDevicesInfoFromNodeStatus indicates an expected call of CreateOpenstackDevicesInfoFromNodeStatus.
func (mr *MockPlatformHelperInterfaceMockRecorder) CreateOpenstackDevicesInfoFromNodeStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenstackDevicesInfoFromNodeStatus", reflect.TypeOf((*MockPlatformHelperInterface)(nil).CreateOpenstackDevicesInfoFromNodeStatus), arg0)
}

// DiscoverSriovDevicesVirtual mocks base method.
func (m *MockPlatformHelperInterface) DiscoverSriovDevicesVirtual() ([]v1.InterfaceExt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverSriovDevicesVirtual")
	ret0, _ := ret[0].([]v1.InterfaceExt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscoverSriovDevicesVirtual indicates an expected call of DiscoverSriovDevicesVirtual.
func (mr *MockPlatformHelperInterfaceMockRecorder) DiscoverSriovDevicesVirtual() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverSriovDevicesVirtual", reflect.TypeOf((*MockPlatformHelperInterface)(nil).DiscoverSriovDevicesVirtual))
}

// GetFlavor mocks base method.
func (m *MockPlatformHelperInterface) GetFlavor() openshift.OpenshiftFlavor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlavor")
	ret0, _ := ret[0].(openshift.OpenshiftFlavor)
	return ret0
}

// GetFlavor indicates an expected call of GetFlavor.
func (mr *MockPlatformHelperInterfaceMockRecorder) GetFlavor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlavor", reflect.TypeOf((*MockPlatformHelperInterface)(nil).GetFlavor))
}

// GetMcClient mocks base method.
func (m *MockPlatformHelperInterface) GetMcClient() versioned.Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMcClient")
	ret0, _ := ret[0].(versioned.Interface)
	return ret0
}

// GetMcClient indicates an expected call of GetMcClient.
func (mr *MockPlatformHelperInterfaceMockRecorder) GetMcClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMcClient", reflect.TypeOf((*MockPlatformHelperInterface)(nil).GetMcClient))
}

// IsHypershift mocks base method.
func (m *MockPlatformHelperInterface) IsHypershift() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHypershift")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHypershift indicates an expected call of IsHypershift.
func (mr *MockPlatformHelperInterfaceMockRecorder) IsHypershift() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHypershift", reflect.TypeOf((*MockPlatformHelperInterface)(nil).IsHypershift))
}

// IsOpenshiftCluster mocks base method.
func (m *MockPlatformHelperInterface) IsOpenshiftCluster() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpenshiftCluster")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOpenshiftCluster indicates an expected call of IsOpenshiftCluster.
func (mr *MockPlatformHelperInterfaceMockRecorder) IsOpenshiftCluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpenshiftCluster", reflect.TypeOf((*MockPlatformHelperInterface)(nil).IsOpenshiftCluster))
}
